// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBr3kDt_-WmqxXkVSlxyPle7XAbrgcRHo',
    appId: '1:13158533461:web:118e6c10b556e6bd6287dc',
    messagingSenderId: '13158533461',
    projectId: 'cookly-495b4',
    authDomain: 'cookly-495b4.firebaseapp.com',
    storageBucket: 'cookly-495b4.appspot.com',
    measurementId: 'G-S3NFN865JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOq54ib7TjYiD_N9wlRM6SH6qWEV12xw',
    appId: '1:13158533461:android:3aa0351c965becba6287dc',
    messagingSenderId: '13158533461',
    projectId: 'cookly-495b4',
    storageBucket: 'cookly-495b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXAgqwSZ81MOec6UhVMUYPX43Xw0X3zU',
    appId: '1:13158533461:ios:95c92b7213ebac9c6287dc',
    messagingSenderId: '13158533461',
    projectId: 'cookly-495b4',
    storageBucket: 'cookly-495b4.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXAgqwSZ81MOec6UhVMUYPX43Xw0X3zU',
    appId: '1:13158533461:ios:95c92b7213ebac9c6287dc',
    messagingSenderId: '13158533461',
    projectId: 'cookly-495b4',
    storageBucket: 'cookly-495b4.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBr3kDt_-WmqxXkVSlxyPle7XAbrgcRHo',
    appId: '1:13158533461:web:91a0d84aef0b973f6287dc',
    messagingSenderId: '13158533461',
    projectId: 'cookly-495b4',
    authDomain: 'cookly-495b4.firebaseapp.com',
    storageBucket: 'cookly-495b4.appspot.com',
    measurementId: 'G-9LRCH9PR0P',
  );
}
